redisson:
  address: redis://127.0.0.1:6379
  timeout: 2000
  connectionPoolSize: 64
  connectionMinimumIdleSize: 10

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000ms
    password:
server:
  port: 8588
